import java.util.Scanner;

public class App {

	public static void main(String[] args) {

		Scanner scan = new Scanner(System.in);
		String value = "";

		Player player1 = new Player();
		Computer computer = new Computer();

		player1.setId(1);
		player1.setName("Player");

		System.out.println("Please enter any one of the values - Rock, Paper, Scissors");

		value = scan.next();

		while (!"Rock".equalsIgnoreCase(value) && !"Paper".equalsIgnoreCase(value) && !"Scissors".equalsIgnoreCase(value)) {
			System.out.println("You have entered Invalid value, Enter any one of Rock, Paper, Scissors ");
			value = scan.next();
		}

		player1.setValue(value);
		computer.setValue();
		computer.setId(2);
		computer.setName("Computer");

		System.out.println("The value generated by Computer is - " + computer.getValue() + "\n");

		if (player1.getValue().equalsIgnoreCase(computer.getValue())) {
			System.out.println("It is a tie");
		} else {
			Player winner = new Game().play(player1, computer);

			System.out.println(winner.getName() + " wins");
		}

		scan.close();
	}

}
